pipeline {
    agent any

    environment {
        PYTHON_VENV = 'venv'
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Namisi-Aaron/alx-backend-python.git'
            }
        }

        stage('Setup Python') {
            steps {
                sh '''
                    python3 -m venv ${PYTHON_VENV}
                    source ${PYTHON_VENV}/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    source ${PYTHON_VENV}/bin/activate
                    python manage.py test
                '''
            }
        }
    }

    post {
        success {
            echo 'Build and tests passed!'
        }
        failure {
            echo 'Build failed. Check logs.'
        }
    }
}