pipeline {
    agent any

    environment {
        PYTHON_VENV = 'venv'
        DOCKER_IMAGE = 'messaging-app'
        DOCKER_TAG = 'latest'
        DOCKER_CREDENTIALS_ID = ''
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                url: 'https://github.com/Namisi-Aaron/alx-backend-python.git'
            }
        }

        stage('Verify Python') {
            steps {
                sh 'which python3 || echo "Python 3 is not installed"'
                sh 'python3 --version || echo "Python 3 is not installed"'
            }
        }

        stage('Setup Python') {
            steps {
                sh '''
                    #!/bin/bash
                    python3 -m venv venv
                    source venv/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    source venv/bin/activate
                    python manage.py test
                '''
            }
        }
    }

    post {
        success {
            echo 'Build and tests passed!'
        }
        failure {
            echo 'Build failed. Check logs.'
        }
    }
}
